export const translations = {
  en: {
    tutors: "TUTORS",
    tutorials: "Tutorials",
    caseStudies: "Case studies",
    resources: "Resources",
    improveSkills: "Improve your skills by",
    studyWithCoding: "study with coding",
    marketingCampaigns: "Create, launch, and iterate on new marketing campaigns without distracting your product team.",
    getStarted: "Get started",
    ourFeatures: "Our Features Special For You",
    specialFeatures: "We provide various special features for all of you",
    bestTutors: "Best Tutors",
    designVision: "Bring your design vision to life in clean, semantic HTML5",
    flexible: "Flexible",
    marketingTools: "Connect your marketing tools with built-in integrations",
    easyAccess: "Easy Access",
    webLanguage: "The language for building web pages",
    goLive: "Go live on a fast, reliable, and hassle-free hosting network that scales with your business with one click and go code!",
    tryItYourself: "Try it Yourself",
    showcase: "Showcase",
    showcaseContent: "Get inspired by the incredible websites built by members of the community",
    university: "University",
    universityContent: 'Browse hundreds of in-depth videos, courses, and guides to get up and running fast',
    choosePackage: "Choose your package",
    providePackages: "We provide various types of packages just for you",
    upgradeSkills: "Start upgrading your skills free for this month",
    buildSite: "Build your site for free and take as long as you need",
  },
  vi: {
    tutors: "GIẢNG VIÊN",
    tutorials: "Hướng dẫn",
    caseStudies: "Nghiên cứu điển hình",
    resources: "Tài nguyên",
    improveSkills: "Nâng cao kỹ năng của bạn bằng",
    studyWithCoding: "học tập với lập trình",
    marketingCampaigns: "Tạo, khởi chạy và cải tiến các chiến dịch tiếp thị mới mà không làm phân tán nhóm sản phẩm của bạn.",
    getStarted: "Bắt đầu",
    ourFeatures: "Các tính năng đặc biệt dành cho bạn",
    specialFeatures: "Chúng tôi cung cấp nhiều tính năng đặc biệt cho tất cả các bạn",
    bestTutors: "Gia sư tốt nhất",
    designVision: "Biến tầm nhìn thiết kế của bạn thành hiện thực với HTML5 sạch và có cấu trúc",
    flexible: "Linh hoạt",
    marketingTools: "Kết nối các công cụ tiếp thị của bạn với tích hợp sẵn",
    easyAccess: "Truy cập dễ dàng",
    webLanguage: "Ngôn ngữ để xây dựng trang web",
    goLive: "Triển khai trên mạng lưu trữ nhanh, đáng tin cậy và không rắc rối, có thể mở rộng theo doanh nghiệp của bạn chỉ với một cú nhấp chuột và đi cùng mã!",
    tryItYourself: "Thử ngay",
    showcase: "Trưng bày",
    university: "Đại học",
    showcaseContent: "Lấy cảm hứng từ những trang web tuyệt vời được xây dựng bởi các thành viên trong cộng đồng",
    universityContent: "Duyệt qua hàng trăm video chuyên sâu, khóa học và hướng dẫn để bắt đầu nhanh chóng",
    choosePackage: "Chọn gói của bạn",
    providePackages: "Chúng tôi cung cấp nhiều loại gói khác nhau dành riêng cho bạn",

    upgradeSkills: "Bắt đầu nâng cấp kỹ năng của bạn miễn phí trong tháng này",
    buildSite: "Xây dựng trang web của bạn miễn phí và dành bao lâu tùy thích",
  },
};
